# RT-Thread building script for bridge

import rtconfig
Import('RTT_ROOT')
from building import *

# get current directory
cwd = GetCurrentDir()

# The set of source files associated with this SConscript file.
src = Split("""

""")


#add for startup script 

src = src + ['Startup/startup_ARMCM0.s']
src += Glob('StdPeriphDriver/*.c')

#add headfile script 
path = [cwd + '/CMSIS/Include', 
    cwd + '/StdPeriphDriver/inc']

CPPDEFINES = ['USE_DDL_DRIVER', rtconfig.MCU_TYPE, '__DEBUG']

group = DefineGroup('StdPeriph', src, depend = [''], CPPPATH = path, CPPDEFINES = CPPDEFINES)

Return('group')
